// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApEPD1Lsrhm4LDYOHJ0kyvmSc6e3sMp-Q',
    appId: '1:403647213215:web:b08a85c888169d9b687caa',
    messagingSenderId: '403647213215',
    projectId: 'swasthya-setu-3dc5e',
    authDomain: 'swasthya-setu-3dc5e.firebaseapp.com',
    storageBucket: 'swasthya-setu-3dc5e.firebasestorage.app',
    measurementId: 'G-4WPL4TFY70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVgYPDRkB8WrNzsALqVGd_ZpHSHuMGYEE',
    appId: '1:403647213215:android:1763b0c42014ce8f687caa',
    messagingSenderId: '403647213215',
    projectId: 'swasthya-setu-3dc5e',
    storageBucket: 'swasthya-setu-3dc5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzRlVTogeDbl8iwTf2UnNfgvLx9Zj5LxE',
    appId: '1:403647213215:ios:3c0fcae70573e160687caa',
    messagingSenderId: '403647213215',
    projectId: 'swasthya-setu-3dc5e',
    storageBucket: 'swasthya-setu-3dc5e.firebasestorage.app',
    iosBundleId: 'com.example.swasthyaSetu',
  );

}